name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Missed arguments test
        id: missed_arguments_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: Missed arguments test
          setup-command: ''
          command: make test ARG=1
          timeout: 10
          max-score: 10
      - name: Square file size test
        id: square_file_size_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: Square file size test
          setup-command: ''
          command: make test ARG=2
          timeout: 10
          max-score: 10
      - name: File size test
        id: file_size_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: File size test
          setup-command: ''
          command: make test ARG=3
          timeout: 10
          max-score: 10
      - name: 2 x 2 matrix test
        id: two_x_two_matrix_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: 2 x 2 matrix test
          setup-command: ''
          command: make test ARG=4
          timeout: 10
          max-score: 10
      - name: 10 x 10 matrix test
        id: ten_x_ten_matrix_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: 10 x 10 matrix test
          setup-command: ''
          command: make test ARG=5
          timeout: 10
          max-score: 10
      - name: 100 x 100 matrix test
        id: hundred_x_hundred_matrix_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: 100 x 100 matrix test
          setup-command: ''
          command: make test ARG=6
          timeout: 10
          max-score: 10
      - name: 1024 x 1024 matrix test
        id: one_thousand_twenty_four_x_one_thousand_twenty_four_matrix_test
        uses: education/autograding-command-grader@v1
        with:
          test-name: 1024 x 1024 matrix test
          setup-command: ''
          command: make test ARG=7
          timeout: 10
          max-score: 20
      - name: Are there n processes?
        id: are_there_n_processes
        uses: education/autograding-command-grader@v1
        with:
          test-name: Are there n processes?
          setup-command: ''
          command: make test ARG=8
          timeout: 10
          max-score: 20
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          MISSED_ARGUMENTS_TEST_RESULTS: ${{ steps.missed_arguments_test.outputs.result }}
          SQUARE_FILE_SIZE_TEST_RESULTS: ${{ steps.square_file_size_test.outputs.result }}
          FILE_SIZE_TEST_RESULTS: ${{ steps.file_size_test.outputs.result }}
          TWO_X_TWO_MATRIX_TEST_RESULTS: ${{ steps.two_x_two_matrix_test.outputs.result }}
          TEN_X_TEN_MATRIX_TEST_RESULTS: ${{ steps.ten_x_ten_matrix_test.outputs.result }}
          HUNDRED_X_HUNDRED_MATRIX_TEST_RESULTS: ${{ steps.hundred_x_hundred_matrix_test.outputs.result }}
          ONE_THOUSAND_TWENTY_FOUR_X_ONE_THOUSAND_TWENTY_FOUR_MATRIX_TEST_RESULTS: ${{ steps.one_thousand_twenty_four_x_one_thousand_twenty_four_matrix_test.outputs.result }}
          ARE_THERE_N_PROCESSES_RESULTS: ${{ steps.are_there_n_processes.outputs.result }}
        with:
          runners: missed_arguments_test,square_file_size_test,file_size_test,two_x_two_matrix_test,ten_x_ten_matrix_test,hundred_x_hundred_matrix_test,one_thousand_twenty_four_x_one_thousand_twenty_four_matrix_test,are_there_n_processes
